name: Build and Test

on:
  push:
    branches: [ main ]  # or 'master' if that's your default branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd ecommerce-frontend
          npm install

      - name: Run tests
        run: |
          cd ecommerce-frontend
          npm test
